### ISSUE TITLE
Hiding Text 

### ISSUE THREAD

**Issue by Badal472** [thelong1EU/SpaceTabLayout#1]
![15497713_1227404344019428_120573064_n](https://cloud.githubusercontent.com/assets/13783485/21132614/f2835dfc-c13a-11e6-9a66-9abf13e01394.png)

unable to mask background Text when app started. after clicking it works fine. please suggest some fix

**Comment by thelong1EU** [comment]
I'm in it!

**Comment by thelong1EU** [comment]
I'm in it! 😂😂

**Comment by thelong1EU** [comment]
Done! Please compile the latest version @Badal472  :D:D

**Comment by thelong1EU** [comment]
Done! Please compile the latest version @Badal472 :D:D
`compile 'eu.long1:spacetablayout:1.0.4'`

**Comment by xbadal** [comment]
Thanks ! it worked,

**Comment by thelong1EU** [comment]
You're welcome. Thanks for writing!
