### ISSUE TITLE
starting_position doesn't seem to work

### ISSUE THREAD

**Issue by Shailevy** [thelong1EU/SpaceTabLayout#2]
Iv'e tried the the basic sample code and did:
 app:starting_position="one"

The starting position was the center anyway. Tried on LG G3 Android 6.0 stock ROM

I also noticed that if I have more than 3 tabs then the text disappears (I'm ignoring the other issue that was already reported with the text overlapping the icon)

Test with version 1.03 and 1.04

**Comment by thelong1EU** [comment]
did you tried the new release? 1.0.4?

**Comment by Shailevy** [comment]
Yes, just now

**Comment by thelong1EU** [comment]
O, just a sec and I will give it a look. Thanks for writing :D

**Comment by thelong1EU** [comment]
![device-2016-12-13-114552](https://cloud.githubusercontent.com/assets/9283414/21135211/bc2813da-c129-11e6-8ed6-0850c88ac7ca.png)
this is what I get at start with this settings :  
        app:number_of_tabs="three"
        app:starting_position="one"

Please try again to use the `compile 'eu.long1:spacetablayout:1.0.4'`
in your gradle.build file.

**Comment by Shailevy** [comment]
I was just about to write you that it worked :) I guess instant-run misses my version change..

Thanks!
An other issue: If change the tabs count to five I loose the test .. is this 'As Designed' ?

**Comment by Shailevy** [comment]
I mean, there is no "text_four" property so it feels on purppose

**Comment by thelong1EU** [comment]
ooo, now I understand you

**Comment by thelong1EU** [comment]
So I didn't make it to have text above 3 tabs. I think that it is not enough room to proper text. Do you think that it could work?

**Comment by Shailevy** [comment]
I think it's worth a shot, but if the text and icon won't fit than it's not worth the effort

**Comment by thelong1EU** [comment]
I've checked again. There is no proper space for text above 3 tabs. Maybe with a scroll tab that could be possible.

**Comment by thelong1EU** [comment]
Thanks again to writing. Have a grate one.
