### ISSUE TITLE
Four & five icon not changed

### ISSUE THREAD

**Issue by aljanshere** [thelong1EU/SpaceTabLayout#28]

**Comment by aravindmj97** [comment]
Im also having this issue. Please provide a fix for this.

**Comment by kuraydev** [comment]
Edit : Solved it. It is not working on XML part. 
You can set the 4-5th icon programmatically. After initialize the tabLayout, you can set the icons.
Example : 
`tabLayout.initialize(viewPager, supportFragmentManager, fragmentList, savedInstanceState)
   tabLayout.setTabFourIcon(R.drawable.ic_group_people_icon)`
