### ISSUE TITLE
Add shadow on top tabLayout

### ISSUE THREAD

**Issue by ismailxebia** [thelong1EU/SpaceTabLayout#3]
How to add shadow ?

**Comment by thelong1EU** [comment]
??
Can you give me more info?

**Comment by thelong1EU** [comment]
I'm still waiting your answer.

**Comment by JakeWoki** [comment]
Per the material design spec this component should have a default elevation of 8dp and cast a shadow upwards on to the content above it - it doesn't seem to do that currently regardless of elevation being set in the layout or in code.

**Comment by thelong1EU** [comment]
now your talking just a moment

**Comment by thelong1EU** [comment]
What SDK level are you trying on??

**Comment by thelong1EU** [comment]
I'm using level 23 and it has shadow and I didn't to anything.

**Comment by thelong1EU** [comment]
So I didn't find the problem that your are talking about and you didn't give me enough info to help you. So, when you really want help, please write me again. Until then I will close this issue.
