### ISSUE TITLE
All five tab icons with text

### ISSUE THREAD

**Issue by NikhilBorad** [thelong1EU/SpaceTabLayout#4]
How can we add text to all five tabs with icon ?

**Comment by thelong1EU** [comment]
It's not enough space. Send me an image that proves that it fits and I will
help you.

**Comment by NikhilBorad** [comment]
Tiny icons will fits there. bro plz help me  how can i achieve this..

**Comment by thelong1EU** [comment]
Sorry, maybe two weeks from now. 😁 I'm on vacation. But you can still give
me an example that respects material design guidelines and that can fit 5
icons + text

**Comment by NikhilBorad** [comment]
okay man.. will wait two week :+1:

**Comment by NikhilBorad** [comment]
brother need help.. why this all icon is not aligned.. look at this 4th and 5th icon, they are below center line.. any idea..??
![device-2016-12-20-190453](https://cloud.githubusercontent.com/assets/4303001/21352539/f39e1508-c6e7-11e6-99f2-fe57c47ff619.png)

**Comment by thelong1EU** [comment]
Hi!

I need to look at this but I'm on vacation 2 weeks. I'll get back to you
soon.

**Comment by NikhilBorad** [comment]
sent you mail..

**Comment by thelong1EU** [comment]
lung.razvan@gmail.com

**Comment by CQZZ** [comment]
Hello thelong1EU:
How do I add images + text! The inside of the callback methods can appear flash back

**Comment by LakumM** [comment]
how to mack a my own icon? in tab
in your library

**Comment by LakumM** [comment]
please send code.

**Comment by long1eu** [comment]
English?

Pe 12 iul. 2017 16:56, "LakumM" <notifications@github.com> a scris:
