### ISSUE TITLE
Doesn't work well with Snackbar

### ISSUE THREAD

**Issue by pbosoa** [thelong1EU/SpaceTabLayout#6]
When the snackbar dissapears, it leaves the space behind that the snackbar had seated.

**Comment by thelong1EU** [comment]
can you give me a picture?

**Comment by thelong1EU** [comment]
This is what i get:

![snackbar](https://cloud.githubusercontent.com/assets/9283414/21502501/e710fa46-cc58-11e6-8f4f-419e9083a571.gif)

Are you sure that you added 
` app:layout_behavior="eu.long1.spacetablayout.SpaceTabLayoutBehavior" `
to your SpaceTabLayout??
